### ISSUE TITLE
Allow queue reordering for same user jobs

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit#155] opened 2019-04-10 13:43 UTC
Here's an example situation happening right now in the cluster:

```
$ pit status
   JOB   S SINCE        UC% UM% USER       TITLE                RESOURCE
Running:
  4535 RUN 04d 21:05:50  50   0 foo        a job                mlc1[cuda 0-1]
  4583 RUN 01d 19:38:21  50   0 foo        a job                mlc1[cuda 2-3]
  4584 RUN 01d 19:35:54  50   0 foo        a job                mlc1[cuda 4-5]
  4601 RUN 01d 01:37:23  50   0 foo        a job                mlc0[cuda 2-3]
  4603 RUN 00d 23:31:00  13  11 bar        a job                mlc3[cuda 0-7]
  4608 RUN 00d 21:33:37   6   1 bar        a job                mlc2[cuda 0-7]
Waiting:
  4618 WAI 00d 20:07:17   0   0 baz        a job                1:[8:txp]
  4619 WAI 00d 19:47:35   0   0 baz        a job                [txp]
```

User baz has two jobs waiting in queue, one that needs 8 GPUs and one that needs one GPU. There are enough GPUs available to run job 4619, but it must wait behind job 4618. In general the FIFO order is fair across users and avoids starvation of longer jobs; however, from baz's perspective, it'd be strictly better if job 4619 cut in line in front of job 4618. It would not cut in front of another user, increasing the throughput of the system with no downsides.

Could we add some support for this case, recognizing a shorter satisfiable job waiting behind larger jobs of the same user, and move them ahead?

**Comment by tilmankamp** [comment] 2019-04-11 14:07
Duplicate of #41.

**Closed by tilmankamp** 2019-04-11 14:07 UTC
